apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-test-pr-{{ .PR_NUMBER }}
  namespace: prombench-{{ .PR_NUMBER }}
  labels:
    app: prometheus
    prometheus: test-pr-{{ .PR_NUMBER }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      prometheus: test-pr-{{ .PR_NUMBER }}
  template:
    metadata:
      namespace: prombench-{{ .PR_NUMBER }}
      labels:
        app: prometheus
        prometheus: test-pr-{{ .PR_NUMBER }}
    spec:
      serviceAccountName: prometheus
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - prometheus
      securityContext:
        runAsUser: 0
      initContainers:
      - name: prometheus-builder
        image: docker.io/prominfra/prometheus-builder:master
        imagePullPolicy: Always
        env:
        - name: PR_NUMBER
          value: "{{ .PR_NUMBER }}"
        - name: VOLUME_DIR
          value: "/prometheus-builder" # same as mountPath
        - name: GITHUB_ORG
          value: "{{ .GITHUB_ORG }}"
        - name: GITHUB_REPO
          value: "{{ .GITHUB_REPO }}"
        volumeMounts:
        - name: prometheus-executable
          mountPath: /prometheus-builder
      containers:
      - name: prometheus
        image: quay.io/prometheus/busybox:latest
        imagePullPolicy: Always
        # The prometheus-builder takes a while to build
        # so make sure to start it before the release deployment.
        # Mark it ready only when prometheus is started.
        # This way we have the least time difference in the scraped metrics.
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 2
          failureThreshold: 30
        command: ["/usr/bin/prometheus"]
        args: [
          "--web.external-url=http://{{ .DOMAIN_NAME }}/{{ .PR_NUMBER }}/prometheus-pr",
          "--storage.tsdb.path=/prometheus",
          "--config.file=/etc/prometheus/prometheus.yml",
          "--log.level=debug",
          # Custom benchmark.
          "--enable-feature=metadata-wal-records"
        ]
        resources:
          requests:
            cpu: 2
            memory: 20Gi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: instance-ssd
          mountPath: /prometheus
        - name: prometheus-executable
          mountPath: /usr/bin
        ports:
        - name: prom-web
          containerPort: 9090
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-test
      - name: instance-ssd
        hostPath:
          # /mnt is where GKE keeps it's SSD.
          path: /mnt/disks/ssd0
      - name: prometheus-executable
        emptyDir: {}
      terminationGracePeriodSeconds: 300
      nodeSelector:
        node-name: prometheus-{{ .PR_NUMBER }}
        isolation: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-test-pr-{{ .PR_NUMBER }}
  namespace: prombench-{{ .PR_NUMBER }}
  labels:
    app: prometheus
    prometheus: test-pr-{{ .PR_NUMBER }}
spec:
  ports:
  - name: prom-web
    port: 80
    targetPort: prom-web
  selector:
    app: prometheus
    prometheus: test-pr-{{ .PR_NUMBER }}
