zone: {{ .ZONE }}
projectid: {{ .PROJECT_ID }}
cluster:
  name: {{ .CLUSTER_NAME }}
  nodepools:
  # These node-pools will be deployed on triggering benchmark
  - name: prometheus-{{ .PR_NUMBER }}
    initialnodecount: 2
    config:
      machinetype: n1-highmem-8
      imagetype: COS
      disksizegb: 100
      localssdcount: 1  #SSD is used to give fast-lookup to Prometheus servers being benchmarked
      labels:
        isolation: prometheus
        node-type: prometheus-{{ .PR_NUMBER }}
  - name: nodes-{{ .PR_NUMBER }}
    initialnodecount: 1
    config:
      machinetype: n1-highcpu-16
      imagetype: COS
      disksizegb: 100
      localssdcount: 0  #use standard HDD. SSD not needed for fake-webservers.
      labels:
        isolation: none
        node-type: nodes-{{ .PR_NUMBER }}