apiVersion: v1
kind: ConfigMap
metadata:
  name: amGithubNotifier-templates
data:
  default: |
    Alertmanager URL: {{ "{{" }} .Data.ExternalURL {{ "}}" }}
    ---
    {{ "{{" }} index .Data.Alerts[0].Annotations "description" {{ "}}" }}

  benchmarkTestsRunning: |
    Benchmark running for more than three days. Please consider stopping the benchmark
    or silencing this alert.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amGithubNotifier
  labels:
    app: amGithubNotifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amGithubNotifier
  template:
    metadata:
      labels:
        app: amGithubNotifier
    spec:
      containers:
      - name: amGithubNotifier
        image: docker.io/prombench/amgithubnotifier:0.0.1
        args:
        - "--org=prometheus"
        - "--repo=prometheus"
        - "--template-dir-path=/etc/amGithubNotifier/templates"
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: templates
          mountPath: /etc/amGithubNotifier/templates
        ports:
        - name: amGithubNotifier-webhook
          containerPort: 8080
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      - name: templates
        configMap:
          name: amGithubNotifier-templates
      terminationGracePeriodSeconds: 300
      nodeSelector:
        cloud.google.com/gke-nodepool: prow
---
apiVersion: v1
kind: Service
metadata:
  name: amGithubNotifier
  labels:
    app: amGithubNotifier
spec:
  type: ClusterIP
  ports:
  - name: amGithubNotifier-webhook
    port: 80
    targetPort: amGithubNotifier-webhook
  selector:
    app: amGithubNotifier
