apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-core
  labels:
    app: grafana
    component: core
spec:
  replicas: 1
  selector:
    matchLabels:
        app: grafana
        component: core
  template:
    metadata:
      labels:
        app: grafana
        component: core
    spec:
      serviceAccountName: prometheus
      containers:
      - image: grafana/grafana:5.0.0
        name: grafana-core
        imagePullPolicy: IfNotPresent
        env:
          - name: GF_PATHS_PROVISIONING
            value: "/opt/grafana-provision"
          - name: GF_SERVER_ROOT_URL
            value: "http://{{ .DOMAIN_NAME }}/grafana"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_NAME
            value: "Main Org."
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - name: grafana-persistent-storage
          mountPath: /var
        - name: grafana-datasources
          mountPath: /opt/grafana-provision/datasources
        - name: grafana-dashboard-provision
          mountPath: /opt/grafana-provision/dashboards
        # dashboards json are saved in the path mentioned in grafana-dashboard-provision
        - name: grafana-dashboards
          mountPath: /grafana-dashboards
        ports:
        - name: grafana-web
          containerPort: 3000
      volumes:
      - name: grafana-persistent-storage
        emptyDir: {}
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboard-provision
        configMap:
          name: grafana-dashboard-provision
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      nodeSelector:
        cloud.google.com/gke-nodepool: prow
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    component: core
spec:
  type: NodePort
  ports:
    - name: grafana-web
      port: 80
      targetPort: grafana-web
  selector:
    app: grafana
    component: core

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-grafana
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # rewrite-target is required for grafana to work properly in subpath
    # TODO: remove after upgrading grafana : https://github.com/grafana/grafana/pull/17048
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: grafana-web
        path: /grafana(/|$)(.*)
