projectid: {{ .PROJECT_ID }}
zone: {{ .ZONE }}
cluster:
  name: {{ .CLUSTER_NAME }}
  initialclusterversion: 1.14
  nodepools:
  # This node-pool will be used for running monitoring components
  - name: main-node
    initialnodecount: 1
    config:
      machinetype: n1-standard-4
      imagetype: COS
      disksizegb: 300
      labels:
        node-type: main-node
