cluster:
  name: {{ .CLUSTER_NAME }}
  version: 1.14
  rolearn: {{ .EKS_CLUSTER_ROLE_ARN }}
  resourcesvpcconfig:
    endpointpublicaccess: true
    subnetids:
      {{ range $subnetId := split .EKS_SUBNET_IDS .SEPARATOR }}
      - {{ $subnetId }}
      {{ end }}
nodegroups:
  - nodegroupname: main-node
    noderole: {{ .EKS_WORKER_ROLE_ARN }}
    disksize: 300
    subnets:
      {{ range $subnetId := split .EKS_SUBNET_IDS .SEPARATOR }}
      - {{ $subnetId }}
      {{ end }}
    instancetypes:
      - t3.xlarge
    scalingconfig:
      desiredsize: 1
      maxsize: 1
      minsize: 1
    labels:
      node-name: main-node
